- DocumentsApi/Properties/launchSettings.json
- README.md
Tidy up readme and launchSettings.json so we can locally run DocumentApi on port `5001` and EvidenceApi on `5000`
> Tidy up readme and launchSettings.json

- DocumentsApi/serverless.yml
I have converted our "secret" SSM params from type String to type SecureString, so that they are encrypted at rest.
We need to tell serverless to decrypt them before injecting them as environment variables, otherwise we will get the encrypted value.
It seems that terraform does this by default.
> Decrypt SSM params of type SecureString

- DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
- DocumentsApi.Tests/V1/UseCase/UpdateClaimStateUseCaseTests.cs
- DocumentsApi/ServiceConfigurator.cs
- DocumentsApi/V1/Boundary/Request/ClaimRequest.cs
- DocumentsApi/V1/Boundary/Request/ClaimUpdateRequest.cs
- DocumentsApi/V1/Controllers/ClaimsController.cs
- DocumentsApi/V1/Factories/EntityFactory.cs
- DocumentsApi/V1/Gateways/DocumentsGateway.cs
- DocumentsApi/V1/Gateways/Interfaces/IDocumentsGateway.cs
- DocumentsApi/V1/UseCase/CreateClaimUseCase.cs
- DocumentsApi/V1/UseCase/Interfaces/IUpdateClaimStateUseCase.cs
- DocumentsApi/V1/UseCase/UpdateClaimStateUseCase.cs
https://hackney.atlassian.net/browse/DES-210
- Added `ValidUntil ` to `ClaimRequest` because I wanted to following `RetentionExpiresAt` where EvidenceAPI provides the default value (3 months)
> DES-210: Process provided validity time

- terraform/staging/main.tf
Reference subnets by name tag instead of type tag as the latter does not exist
> Reference subnets by name

- DocumentsApi/python/lambda-orchestrator.py
https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-254
Updated the lambda orchestrator to call another lambda (DocumentsS3Function in serverless) when the file doesn't contain malware.
> Update lambda orchestrator to call DocumentsS3Function(serverless)

- .circleci/config.yml
We should deploy the app only if database migration finishes successfully, otherwise we may deploy code changes that depend on database changes which weren't deployed
> DES-254: app deployment should be dependent on database migration

- DocumentsApi/serverless.yml
With https://hackney.atlassian.net/browse/DES-309 files are uploaded via DocumentsAPI so CORS does not need to be configured on our bucket
> Remove S3 bucket CORS config

- DocumentsApi.Tests/V1/UseCase/FindClaimByIdUseCaseTests.cs
- DocumentsApi/V1/UseCase/FindClaimByIdUseCase.cs
This commit quickly fixes the issue where an officer was not able to view the claims and documents of a resident, because one claim was expired. This fix now allows expired claims to render on the frontend.
> Amend FindClaimByIdUseCase so it returns expired claims

- DocumentsApi/V1/Node/index.js
The call the Amazon S3 is currently returning a 200, but the object is empty. We think that the call is not awaiting the presigned url to come back from S3. We tried turning the function into an async, but this conflicts with the behaviour of the callback.
S3 returns a Promise object, so we need to handle this using .then.
> Change return to handle Promise object

- DocumentsApi/python/lambda-orchestrator.py
We need to check for MIME types when we upload documents to S3.
Why? This is because after our pen-test, it was highlighted that we need to do client- and server-side validation of Content-Types. Due to our new approach to uploading documents, we can no longer enforce a Content-Type check at the server, neither when we are specifying a condition for the policy (because we don't know what the Content-Type is at this stage). However, we can do this when the Document Orchestrator lambda is run to scan for malware.
We have introduced a check for accepted MIME types in this script. If a file does not pass the check, it is deleted from the bucket. The documents-api database is then not updated with the file metadata needed for the document entity and …
> Amend document orchestrator to check for MIME types

- DocumentsApi/V1/Node/index.js
- DocumentsApi/python/lambda-orchestrator.py
Content Type that is being returned from AWS is `'ContentType': '""'`. We wonder whether this content type is coming from the file itself or from when we declare it as part of the upload policy. We'll upload a file that specifies PNG to test this.
Add content type to policy and remove erroring print statement
> Add content type to policy and remove print statement

- DocumentsApi/V1/Node/index.js
- DocumentsApi/python/lambda-orchestrator.py
Validation for content-type will not work at the moment.
We've discovered that `head_object` does not read from the file in the bucket directly, but instead from the content-type that was sent in the request when it was uploaded. This value could be different from the file itself, e.g. we sent a PNG but set the content-type to image/jpeg and the result from `head_object` was image/jpeg. 
We've commented out the content-type validation in the orchestrator for now and will discuss solutions.
For the frontend work that we're about to do, we've changed the policy to accept 50mb and all content-types.
Are there any next steps that need to be addressed after merging this PR? Add them here.
> Comment out file type validation and amend policy

- DocumentsApi/python/lambda-orchestrator.py
S3 only reads content-type from the upload request header, so we need a solution that reads the MIME type directly from the file.
We're trying python/magic to see if this works.
> Add mime type print statement from python/magic library

- DocumentsApi.Tests/V1/E2ETests/DocumentsTests.cs
- DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
- DocumentsApi.Tests/V1/UseCase/CreateUploadPolicyUseCaseTests.cs
- DocumentsApi/DocumentsApi.csproj
- DocumentsApi/V1/Gateways/S3Gateway.cs
https://hackney.atlassian.net/browse/DOC-611
The upload path for using a presigned url from S3 is working, we just need to add in the unit tests at the gateway and use case level, and E2E tests at the controller level.
Added in the tests and made sure that the Node files were copied to the Output directory, as the final E2E test was failing because index.js was not available in the container or locally.
None, onto the download path after this!
> Add tests for  upload via S3 presigned url path

- DocumentsApi/python/lambda-orchestrator.py
https://hackney.atlassian.net/browse/DOC-587
We would like to print the MIME type of a file in the Python script by using shell/system command `file`
Adding `shell=True` to make the command run in the shell.
> Add shell=True to subprocess argument to invoke system shell

- DocumentsApi/python/lambda-orchestrator.py
We're having issues running a bash command from the Python script, because the command for `file` cannot be found. We think it's because the operating system (Amazon Linux 2) in the lambda is not using the bash interpreter to run the command.
Hopefully, by using the os library, we can run `which` to find the correct location of the interpreter (because bash is included in AL2), using its default shell interpreter (/bin/sh).
> Add check for bash location using os library

- DocumentsApi/serverless.yml
https://hackney.atlassian.net/browse/DOC-611
Add CORS configuration to be able to use the S3 pre-signed URL for the upload
> Add CORS configuration in serverless

- DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
- DocumentsApi/V1/Controllers/ClaimsController.cs
Legacy work from https://hackney.atlassian.net/browse/DOC-675
We've updated the behaviour of CreateClaimAndUploadPolicy endpoint, we just need to make sure that the documentation, endpoint makes sense and the happy path is covered by a test.
- Swagger comments updated
- endpoint updated
- existing tests updated
- new test for happy path added
After an engineering team discussion, we did identify that 500 errors are not being handled correctly. We're raising a bug ticket for this to add a global 500 catch.
> Amend CreateClaimAndUploadPolicy endpoint and add test

- DocumentsApi.Tests/DocumentsApi.Tests.csproj
- DocumentsApi.Tests/V1/Controllers/Filters/HandleExceptionAttributeTests.cs
- DocumentsApi.Tests/V1/E2ETests/HealthCheckTests.cs
- DocumentsApi/Program.cs
- DocumentsApi/Startup.cs
- DocumentsApi/V1/Controllers/Filters/HandleExceptionAttribute.cs
https://hackney.atlassian.net/browse/DOC-686
When an exception wasn't handled by the API the response body contained the entire stack trace revealing too much about the internals of the service. Also, unhandled exceptions weren't logged.
Added a filter for handling unhandled exceptions and have applied it globally.
> Add HandleExceptionAttribute

- DocumentsApi/V1/Boundary/Request/ClaimRequest.cs
- DocumentsApi/V1/Domain/Document.cs
- DocumentsApi/V1/UseCase/CreateClaimUseCase.cs
https://hackney.atlassian.net/browse/DOC-1134
Added the ability to specify a target ID and a name for the document when making a request to create a claim.
- Updated `ClaimRequest` to include `TargetId` and `DocumentName`
- Updated `CreateClaimUseCase` to build a new claim containing `DocumentName` or not based on the existence of the `DocumentName` parameter on the `ClaimRequest`
- Added a constructor to the `Document` class to be able to specify the `Name` of the new documented created
The next step is to create the endpoint that allows retrieving multiple claims containing the `TargetId` provided in the request.
> Add targetId and DocumentName to ClaimRequest

- .circleci/config.yml
- .env.example
- DocumentsApi.Tests/Dockerfile
- DocumentsApi.Tests/DocumentsApi.Tests.csproj
- DocumentsApi.Tests/V1/Authorization/AuthorizeByGroupsTests.cs
- DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
- DocumentsApi.Tests/V1/E2ETests/Constants.cs
- DocumentsApi.Tests/compose.yml
- DocumentsApi/Dockerfile
- DocumentsApi/DocumentsApi.csproj
- DocumentsApi/Startup.cs
- DocumentsApi/V1/Authorization/AuthorizeByGroups.cs
- DocumentsApi/V1/Authorization/EnvironmentVariableNullException.cs
- DocumentsApi/V1/Controllers/ClaimsController.cs
- DocumentsApi/compose.yml
- DocumentsApi/serverless.yml
- NuGet.Config
- README.md
- database/Dockerfile
- database/compose.yml
https://hackney.atlassian.net/browse/DOC-1141
Added authorization using google groups to the endpoint used to get claims by target ID.
- The authorization is using the [lbh-core](https://github.com/LBHackney-IT/lbh-core) library
- Added changes to the docker files and docker-compose files to allow the usage of the lbh-core library
- Added NuGet package configuration (which is using a secret token to allow usage)
- Updated tests to contain the authorization header
- Updated the README file with information regarding setting up the new token needed to use the lbh-core library
> Add authorization using google groups to the endpoint to get claims by target ID

- DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
- DocumentsApi.Tests/V1/Factories/EntityFactoryTests.cs
- DocumentsApi.Tests/V1/Factories/ResponseFactoryTest.cs
- DocumentsApi.Tests/V1/Validators/ClaimRequestValidatorTests.cs
- DocumentsApi/Migrations/20220926152941_AddDescriptionToDocument.Designer.cs
- DocumentsApi/Migrations/20220926152941_AddDescriptionToDocument.cs
- DocumentsApi/V1/Boundary/Request/ClaimRequest.cs
- DocumentsApi/V1/Boundary/Response/DocumentResponse.cs
- DocumentsApi/V1/Domain/Document.cs
- DocumentsApi/V1/Factories/DomainFactory.cs
- DocumentsApi/V1/Factories/EntityFactory.cs
- DocumentsApi/V1/Factories/ResponseFactory.cs
- DocumentsApi/V1/Infrastructure/DocumentEntity.cs
- DocumentsApi/V1/UseCase/CreateClaimAndS3UploadPolicyUseCase.cs
- DocumentsApi/V1/UseCase/CreateClaimUseCase.cs
- DocumentsApi/V1/Validators/ClaimRequestValidator.cs
https://hackney.atlassian.net/browse/DOC-1185
When people make a request to create a claim in Documents API, this creates a document. We need this document entity to hold a new field: `description`, so that people can give description of up to 1000 characters.
Added a migration to the documents table to add the `Description` field.
Changes relevant Request, Response, Domain and Entity classes.
Added validation to check for up to 1000 characters
Double checked the code for the endpoints that deal with claims to make sure they're returning `Description` (and Name for the GetClaimAndS3 one) or handling a request to add `Description`.
Refactored the ClaimBuilder
> Doc 1185: Add description to document data

- DocumentsApi.Tests/V1/Validators/ClaimRequestValidatorTests.cs
- DocumentsApi/DocumentsApi.csproj
https://hackney.atlassian.net/browse/DOC-1304
In a separate PR we have added "process" to the valid TargetType values in Hackney.Core.Enums
This PR aims tp updated this API's .csproj to reflect the version change  
One test has also been updated to reflect this
> DOC-1304: Updated NuGet enums version to include process

- docs/adr/0003-use-s3-for-uploading-and-fetching-documents.md
- docs/adr/README.md
We need to add an ADR for the new way of uploading documents in Documents API -- using the S3 presigned url instead of passing around a base-64 string.
Added an adr.
> Add adr for s3 upload process

- .circleci/config.yml
- DocumentsApi.Tests/Dockerfile
- DocumentsApi.Tests/DocumentsApi.Tests.csproj
- DocumentsApi.Tests/GlobalSetup.cs
- DocumentsApi.Tests/V1/E2ETests/HealthCheckTests.cs
- DocumentsApi/Dockerfile
- DocumentsApi/DocumentsApi.csproj
- DocumentsApi/Startup.cs
- DocumentsApi/build.sh
- DocumentsApi/serverless.yml
- README.md
- database/Dockerfile
https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1076
This PR upgrades the Documents API to run on Dotnet 6, replacing Dotnet 3.1 which is coming to end of life. Packages have been upgraded, and refactoring has been done where methods are no longer supported.
Test in staging, once the Evidence API upgrade has also been completed.
> DOC-1076 - Upgrade to Dotnet 6.0
