LBHackney-IT/documents-api

README.md

Add swagger to readme

---

docker-compose.yml

Tidy up dev and test database ports to match EvidenceApi config

Tidy up dev and test database ports to match EvidenceApi config

---

DocumentsApi.Tests/V1/Domain/ClaimTests.cs
DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/E2ETests/DocumentsTests.cs
DocumentsApi.Tests/V1/Factories/ResponseFactoryTest.cs
DocumentsApi.Tests/V1/Gateways/DocumentsGatewayTests.cs
DocumentsApi.Tests/V1/TestDataHelper.cs
DocumentsApi.Tests/V1/UseCase/CreateClaimUseCaseTests.cs
DocumentsApi.Tests/V1/UseCase/FindClaimByIdUseCaseTests.cs
DocumentsApi/ServiceConfigurator.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/Domain/Claim.cs
DocumentsApi/V1/Gateways/DocumentsGateway.cs
DocumentsApi/V1/Gateways/Interfaces/IDocumentsGateway.cs
DocumentsApi/V1/UseCase/FindClaimByIdUseCase.cs
DocumentsApi/V1/UseCase/Interfaces/IFindClaimByIdUseCase.cs

Allow clients to fetch a document by ID

DES-60 Find document by ID

---

.circleci/config.yml
DocumentsApi.Tests/V1/Gateways/DocumentsGatewayTests.cs
DocumentsApi/V1/Gateways/DocumentsGateway.cs

When we were getting the claim we were not attaching the document to it so it was always null. Now it should always fetch the document along with the claim.

Update FindClaim gateway function to attach the document to the claim

---

.gitignore
terraform/production/main.tf
terraform/staging/main.tf

Update db version to 11.10 and added node_modules to gitignore

Update postgres version and gitignore node_modules

---

DocumentsApi/serverless.yml

https://hackney.atlassian.net/browse/DES-172
Increase lambda timeout to 30 seconds

DES-172: increase lambda timeout to 30 seconds

---

DocumentsApi/ServiceConfigurator.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/Gateways/Interfaces/IS3Gateway.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/UseCase/DownloadDocumentUseCase.cs
DocumentsApi/V1/UseCase/Interfaces/IDownloadDocumentUseCase.cs

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-57
Add API endpoint, gateway function and use case to generate a pre-signed download URL for a document in S3.

Generate download URL for documents

---

DocumentsApi/V1/Boundary/Request/DownloadDocumentRequest.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/UseCase/DownloadDocumentUseCase.cs
DocumentsApi/V1/UseCase/Interfaces/IDownloadDocumentUseCase.cs

- Refactor document download URL endpoint to receive a request object

Refactor document download url api endpoint

---

DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
DocumentsApi.Tests/V1/UseCase/DownloadDocumentUseCaseTests.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/UseCase/DownloadDocumentUseCase.cs

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-57
- Added tests to cover the s3 download url feature (gateway tests, use case tests, e2e tests)

Add tests for s3 download url

---

terraform/staging/main.tf

Applying this PR https://github.com/LBHackney-IT/evidence-api/pull/48 to DocumentsAPI

Bump the db instance size

---

DocumentsApi.Tests/V1/Domain/ClaimTests.cs
DocumentsApi.Tests/V1/Domain/DocumentTests.cs
DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/Gateways/DocumentsGatewayTests.cs
DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
DocumentsApi.Tests/V1/Infrastructure/DocumentsContextTests.cs
DocumentsApi.Tests/V1/TestDataHelper.cs
DocumentsApi.Tests/V1/UseCase/CreateClaimUseCaseTests.cs
DocumentsApi.Tests/V1/UseCase/FindClaimByIdUseCaseTests.cs
DocumentsApi.Tests/V1/Validators/ClaimRequestValidatorTests.cs
DocumentsApi/V1/Domain/Claim.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/Infrastructure/DocumentsContext.cs
DocumentsApi/V1/Validators/ClaimRequestValidator.cs

https://hackney.atlassian.net/browse/DES-204

DES-204: Store UTC timestamps for date fields

---

DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/TestDataHelper.cs
DocumentsApi/Migrations/20210407123814_AddValidUntilToClaims.Designer.cs
DocumentsApi/Migrations/20210407123814_AddValidUntilToClaims.cs
DocumentsApi/V1/Boundary/Response/ClaimResponse.cs
DocumentsApi/V1/Domain/Claim.cs
DocumentsApi/V1/Factories/DomainFactory.cs
DocumentsApi/V1/Factories/EntityFactory.cs
DocumentsApi/V1/Factories/ResponseFactory.cs
DocumentsApi/V1/Infrastructure/ClaimEntity.cs
DocumentsApi/V1/UseCase/CreateClaimUseCase.cs
database/schema.sql

https://hackney.atlassian.net/browse/DES-210

DES-210: add ValidUntil field to claims

---

.circleci/config.yml
terraform/staging/main.tf

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-252
- Updated the CircleCI config to use a new IAM role and context to deploy to a new AWS account
- Updated terraform state bucket name

Update circleci config and terraform to deploy to a new aws account

---

terraform/staging/main.tf

Comment out postgres config in terraform

Comment out postgres config in terraform

---

DocumentsApi/serverless.yml

Add package back to serverless

Add package back to serverless

---

DocumentsApi/serverless.yml

Comment out DocumentsApi lambda

Comment out DocumentsApi lambda

---

DocumentsApi/serverless.yml

DES-254: bucket name needs to be unique across regions

---

DocumentsApi/serverless.yml

FIx indentation in serverless yml

Fix yml syntax error

---

DocumentsApi/build.sh

DES-254: create a zip with the contents of the python directory

---

DocumentsApi.Tests/V1/E2ETests/DocumentsTests.cs
DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
DocumentsApi/V1/Gateways/S3Gateway.cs

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-255
- Updated the location where documents are uploaded to S3
- Updated the location where documents are downloaded from S3

Update location where documents are uploaded/downloaded

---

DocumentsApi/serverless.yml

DES-254: serverless config with rules and prefix

---

DocumentsApi/V1/UseCase/UpdateUploadedDocumentUseCase.cs
DocumentsApi/python/lambda-orchestrator.py

DES-254: update lambda-orchestrator to trigger DocumentsS3Function

---

DocumentsApi/python/lambda-orchestrator.py
DocumentsApi/serverless.yml

DES-254: drop the environment from our function names

---

DocumentsApi/serverless.yml

DES-252: uncomment out DocumentsApi function

---

DocumentsApi/serverless.yml

DES-252: copy authorizer config from HousingSearchApi

---

.circleci/config.yml

DES-252: update jumpbox SSM param names

---

DocumentsApi/serverless.yml

DES-252: use documents_api_db_traffic-stg

---

DocumentsApi/serverless.yml

DES-252: remove accidental spacing

---

DocumentsApi/V1/UseCase/UpdateUploadedDocumentUseCase.cs
DocumentsApi/serverless.yml

DES-254: lookup object in S3 using the correct key

---

DocumentsApi/python/lambda-orchestrator.py

DES-254: tidy up logging and comments

---

DocumentsApi/python/lambda-orchestrator.py
DocumentsApi/serverless.yml

DES-254: use SSL certificate for lambda orchestrator

---

DocumentsApi/V1/Gateways/S3Gateway.cs

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-278
Change expiration time of the presigned download url link so that it is available for a shorter period of time.

Change expiration time of the presigned download url link

---

DocumentsApi/python/lambda-orchestrator.py
DocumentsApi/serverless.yml

DES-254: remove custom SSL certificate

---

DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
DocumentsApi.Tests/V1/UseCase/DownloadDocumentUseCaseTests.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/Controllers/DocumentsController.cs
DocumentsApi/V1/Gateways/Interfaces/IS3Gateway.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/UseCase/DownloadDocumentUseCase.cs
DocumentsApi/V1/UseCase/Interfaces/IDownloadDocumentUseCase.cs

https://hackney.atlassian.net/browse/DES-308

DES-308: replace download_links with retrieving document directly from S3

---

DocumentsApi/V1/Controllers/ClaimsController.cs

We're waiting for service token, get/documents/token, to be created
https://hackney.atlassian.net/browse/DES-308

DES-308: temporarily expose document download in ClaimsController

---

DocumentsApi/DocumentsApi.csproj
DocumentsApi/V1/Gateways/S3Gateway.cs

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

DES-308: dispose of s3 client earlier; bump s3 sdk version number

---

DocumentsApi/V1/Gateways/S3Gateway.cs

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

DES-208: attempt using GetObjectStreamAsync

---

DocumentsApi/V1/Gateways/S3Gateway.cs

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

DES-308: tweak response ContentType

---

DocumentsApi/V1/Gateways/S3Gateway.cs

Add a summary of the problem and any additional context that helps explain what the issue we're trying to solve is.
Add descriptions of what changes were made to address the problem and provide a solution.
Include any links to commits that introduce significant additions of code if they help explain the process of coming to the solution. e.g Addition of test database setup, addition of first test and production class, removal of buggy code, etc.

DES-308: read as string

---

DocumentsApi.Tests/DocumentsApi.Tests.csproj
DocumentsApi.Tests/IntegrationTests.cs
DocumentsApi.Tests/MockWebApplicationFactory.cs
DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/E2ETests/DocumentsTests.cs
DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
DocumentsApi.Tests/V1/UseCase/DownloadDocumentUseCaseTests.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/Controllers/DocumentsController.cs
DocumentsApi/V1/Gateways/Interfaces/IS3Gateway.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/UseCase/DownloadDocumentUseCase.cs
DocumentsApi/V1/UseCase/Interfaces/IDownloadDocumentUseCase.cs

- remove local testing methods
- add tests

DES-308: move endpoint to documents controller

---

DocumentsApi/DocumentsApi.csproj
DocumentsApi/ServiceConfigurator.cs
DocumentsApi/Startup.cs
DocumentsApi/serverless.yml

https://hackney.atlassian.net/browse/DES-226

DES-226: Enable AWS X-Ray

---

DocumentsApi/ServiceConfigurator.cs

`Entity doesn't exist in AsyncLocal`. I think UseLazyLoadingProxies is causing issues

DES-226: exception thrown during db migration

---

README.md

Add the MIT license because it's a requirement for the service assessment

Refer to license from README

---

DocumentsApi/serverless.yml

See https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html

DES-309: configure API Gateway to accept binary media types

---

DocumentsApi.Tests/V1/E2ETests/DocumentsTests.cs
DocumentsApi.Tests/V1/Factories/DocumentFormatFactoryTests.cs
DocumentsApi.Tests/V1/UseCase/DownloadDocumentUseCaseTests.cs
DocumentsApi.Tests/V1/UseCase/UploadDocumentUseCaseTests.cs
DocumentsApi/ServiceConfigurator.cs
DocumentsApi/V1/Domain/Base64DecodedData.cs
DocumentsApi/V1/Factories/DocumentFormatFactory.cs
DocumentsApi/V1/Factories/Interfaces/IDocumentFormatFactory.cs
DocumentsApi/V1/Gateways/Interfaces/IS3Gateway.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/UseCase/DownloadDocumentUseCase.cs
DocumentsApi/V1/UseCase/UploadDocumentUseCase.cs
DocumentsApi/serverless.yml
docs/adr/0002-use-base64-content-for-file-uploading.md
docs/adr/README.md

https://hackney.atlassian.net/browse/DES-309

DES-309: refactor formatting classes and add tests

---

.circleci/config.yml
.config/dotnet-tools.json
DocumentsApi/DocumentsApi.csproj
DocumentsApi/Startup.cs
DocumentsApi/publish-to-swagger-hub.sh

https://hackney.atlassian.net/browse/DES-143
Builds on https://github.com/LBHackney-IT/cv-19-res-support-v3/pull/69 and extends it to invoke `publish-to-swagger-hub.sh` from CircleCI after `deploy-to-production` finishes successfully

DES-143: Publish Swagger docs on production deployment

---

DocumentsApi.Tests/V1/UseCase/UpdateClaimStateUseCaseTests.cs
DocumentsApi/V1/UseCase/UpdateClaimStateUseCase.cs

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-332
- Add condition so the claim valid date is allowed only if it is in the future

Add condition for claim date to only be allowed if it is in the future

---

.circleci/config.yml

Service account has not been configured correctly and we cannot use this until it has
https://hackney.atlassian.net/browse/DES-143

DES-143: comment out publishing SwaggerDocs

---

.circleci/config.yml

https://hackney.atlassian.net/browse/DES-143
Add configuration to circleci to automatically publish swagger docs on deploy.

Add automatic publish to swagger hub

---

.circleci/config.yml

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-143
Revert oublishing to swagger hub as it is currently failing.

Revert publishing to swagger hub

---

.circleci/config.yml

https://hackney.atlassian.net/jira/software/projects/DES/boards/45?selectedIssue=DES-143
Add config to circleci to publish swagger docs

Publish to swagger hub

---

database/Dockerfile

https://hackney.atlassian.net/browse/DES-352
Change postgres docker image to fix the build issues

Change postgres docker image to fix the build errors

---

.gitignore
DocumentsApi.Tests/V1/Gateways/S3GatewayTests.cs
DocumentsApi/Dockerfile
DocumentsApi/DocumentsApi.csproj
DocumentsApi/ServiceConfigurator.cs
DocumentsApi/V1/Controllers/DocumentsController.cs
DocumentsApi/V1/Domain/S3UploadPolicy.cs
DocumentsApi/V1/Gateways/Interfaces/IS3Gateway.cs
DocumentsApi/V1/Gateways/S3Gateway.cs
DocumentsApi/V1/Node/index.js
DocumentsApi/V1/Node/package-lock.json
DocumentsApi/V1/Node/package.json

Created a spike to test that the S3 POST pre-signed URL is created using Jering.Javascript.NodeJS (alternative to the old NodeServices which is now obsolete)
This will be properly implemented and tested in the future

Add GenerateUploadPolicy spike

---

DocumentsApi/V1/Controllers/DocumentsController.cs
DocumentsApi/V1/Node/index.js

Changed the function signature and call in the JS file to fix an error

Change function call and signature in index js

---

DocumentsApi.Tests/Dockerfile

Install node in the tests docker container

Install node in the tests docker container

---

DocumentsApi/serverless.yml

Adding a lambda layer for node js

Adding a lambda layer for node js

---

.circleci/config.yml

Update circleci config to install node dependencies

Update circleci config to install node dependencies

---

DocumentsApi/V1/Gateways/S3Gateway.cs

Load js from string instead of separate file to test

Load js from string instead of separate file to test

---

DocumentsApi/V1/Gateways/S3Gateway.cs

Update function that calls the js module

Update function that calls the js module

---

DocumentsApi/DocumentsApi.csproj
DocumentsApi/V1/Gateways/S3Gateway.cs

Update config to make the index.js file available on the lambda

Update config to make the index.js file available on the lambda

---

DocumentsApi/V1/Node/index.js

We would like to test that we cannot upload a file larger than 10MB and that we also cannot upload a file that does not match the content-type specified in the policy (in this case, an image/jpeg).
We've changed the content length parameter to 10mb (in bytes) and for the policy to only accept image/jpeg.

Presigned url policy length and content-type test

---

DocumentsApi/V1/Node/index.js

Content-Types will now be checked at the bucket level
Allow any content-type to be uploaded via the presigned url policy
We will now check content-types at the S3 bucket level as part of the lambda orchestrator.

Change policy to accept any Content-Type

---

DocumentsApi/python/lambda-orchestrator.py

Currently, ContentType is returning "" regardless of what file we try to upload (acceptable or not acceptable).
We need to add print statements to see what head_object is returning.

Add print statements

---

DocumentsApi/V1/Controllers/DocumentsController.cs
DocumentsApi/V1/Gateways/Interfaces/IS3Gateway.cs
DocumentsApi/V1/Gateways/S3Gateway.cs

Add pre-signed download URL spike

Add pre-signed download url for S3

---

DocumentsApi/python/lambda-orchestrator.py

The lambda orchestrator currently isn't working due to an imported library -- part of our security work on the upload/download process
We've commented them out for now to return to them later.

Comment out Magic lines

---

DocumentsApi/python/lambda-orchestrator.py

https://hackney.atlassian.net/browse/DOC-587
Temporarily removed the try catch block from the python script to test the python-magic library

Temporarily remove try catch block in the python script for testing

---

DocumentsApi/python/lambda-orchestrator.py

https://hackney.atlassian.net/browse/DOC-587
Trying out a different way of running bash commands in the python script

Update the python script to use different bash commands

---

.circleci/config.yml
DocumentsApi/python/lambda-orchestrator.py

Install python and and python-magic to check document's mime type.

Install python and and python-magic to check document mime type

---

.circleci/config.yml

Install pip in circle config

---

.circleci/config.yml
DocumentsApi/python/requirements.txt

Install python venv and dependencies

Install python venv and dependencies

---

.circleci/config.yml

Error in pipeline due to venv not being installed
We're adding command to install it

Install venv

---

.circleci/config.yml

https://hackney.atlassian.net/browse/DOC-669
Module 'magic' is not being imported
We pulled the zip file locally and it seemed to fail because it couldn't find libmagic. We've included it in the env here.

Install libmagic

---

README.md

Update the README to provide new set up instructions to get envars and new commands.
The README was previously providing make instructions to get the project running that didn't work.

Readme update for start up and testing

---

DocumentsApi/serverless.yml

https://hackney.atlassian.net/browse/DOC-611
Add CORS domains as they were missing

Add CORS domains

---

DocumentsApi/python/build-python.sh
DocumentsApi/python/lambda-orchestrator.py

https://hackney.atlassian.net/browse/DOC-670
- Update path in build-python.sh as it couldn't find the required file at the previously specified location
- Add command to install pip3 in the build-python script so we can install the dependencies

Update path in build-python

---

DocumentsApi/python/lambda-orchestrator.py

https://hackney.atlassian.net/browse/DOC-670
Add mime type check for files downloaded by the lambda orchestrator and refactored return statements

Add mime type check

---

.circleci/config.yml

Fix dotnet-ef version to 6.0.5 to be compatible with .NET 3.1

Fix dotnet ef version

---

DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/Factories/DomainFactoryTests.cs
DocumentsApi.Tests/V1/Factories/EntityFactoryTests.cs
DocumentsApi.Tests/V1/Factories/ResponseFactoryTest.cs
DocumentsApi/Migrations/20220831112638_AddNameToDocumentAndTargetIdToClaim.Designer.cs
DocumentsApi/Migrations/20220831112638_AddNameToDocumentAndTargetIdToClaim.cs
DocumentsApi/V1/Boundary/Response/ClaimAndPreSignedDownloadUrlResponse.cs
DocumentsApi/V1/Boundary/Response/ClaimAndS3UploadPolicyResponse.cs
DocumentsApi/V1/Boundary/Response/ClaimResponse.cs
DocumentsApi/V1/Boundary/Response/DocumentResponse.cs
DocumentsApi/V1/Domain/Claim.cs
DocumentsApi/V1/Domain/Document.cs
DocumentsApi/V1/Factories/DomainFactory.cs
DocumentsApi/V1/Factories/EntityFactory.cs
DocumentsApi/V1/Factories/ResponseFactory.cs
DocumentsApi/V1/Infrastructure/ClaimEntity.cs
DocumentsApi/V1/Infrastructure/DocumentEntity.cs

https://hackney.atlassian.net/browse/DOC-1099
- Added `Name` field to `Document` domain model and entity
- Added `TargetId` field to `Claim` domain mode
- Added `Name` and `TargetId` to response objects
- Updated all factories to include the new properties
- Updated unit and integration tests

Add Name field to Document and TargetId field to Claim

---

DocumentsApi/serverless.yml

Update path for env var to correctly get the value from SSM

Update path for env var to correctly get the value from SSM

---

README.md

Added documentation for setting up the env var needed to run tests locally.

Add more documentation for setting up the env var used in tests

---

DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/UseCase/CreateClaimUseCaseTests.cs
DocumentsApi.Tests/V1/Validators/ClaimRequestValidatorTests.cs
DocumentsApi/DocumentsApi.csproj

https://hackney.atlassian.net/browse/DOC-1321
There's a new version of the Nuget package that handles the TargetType enums
This PR is to update the version used in the API to match it
Updated .csproj file and tests

DOC-1321: New Enums package version

---

DocumentsApi/Startup.cs

Fix env vars loading

---

.gitignore
DocumentsApi/package-lock.json
DocumentsApi/serverless.yml

https://hackney.atlassian.net/jira/software/c/projects/DOC/boards/68?modal=detail&selectedIssue=DOC-1385
This PR adds more detailed lambda monitoring, so we are able to collect performance data.

DOC-1385 - Lambda Performance Monitoring

---

.config/dotnet-tools.json
DocumentsApi.Tests/V1/E2ETests/ClaimsTest.cs
DocumentsApi.Tests/V1/Gateways/DocumentsGatewayTests.cs
DocumentsApi.Tests/V1/UseCase/UpdateClaimsGroupIdUseCaseTests.cs
DocumentsApi/ServiceConfigurator.cs
DocumentsApi/V1/Boundary/Request/ClaimsUpdateRequest.cs
DocumentsApi/V1/Controllers/ClaimsController.cs
DocumentsApi/V1/Gateways/DocumentsGateway.cs
DocumentsApi/V1/Gateways/Interfaces/IDocumentsGateway.cs
DocumentsApi/V1/UseCase/Interfaces/IUpdateClaimsGroupIdUseCase.cs
DocumentsApi/V1/UseCase/UpdateClaimsGroupIdUseCase.cs

https://hackney.atlassian.net/browse/DOC-1352
- Added endpoint to update the `groupId` of the claims found based on another groupId
- Added gateway function and new use case
- Added unit and integration tests

Add endpoint to replace groupId for claims

---

.circleci/config.yml
DocumentsApi.Tests/Dockerfile
DocumentsApi.Tests/DocumentsApi.Tests.csproj
DocumentsApi.Tests/V1/E2ETests/HealthCheckTests.cs
DocumentsApi/Dockerfile
DocumentsApi/DocumentsApi.csproj
DocumentsApi/build.cmd
DocumentsApi/build.sh
DocumentsApi/serverless.yml
Makefile
README.md
database/Dockerfile

https://hackney.atlassian.net/browse/TS-1891
We need to upgrade our .NET projects to 8.0 before the current version/s become unsupported by AWS.

Ts 1891 4 documents api upgrade framework version

---

.circleci/config.yml
DocumentsApi/serverless.yml

**What**
`[!] Invalid configuration encountered
at 'provider': unrecognized property 'usagePlan'`
`[!] Function DocumentsApi has a timeout of 30 seconds, but it is attached to an API Gateway with a timeout of 29 seconds`
Removes unnecessary usagePlan config and sets the timeout to match gateway.

Serverless config

---

DocumentsApi/serverless.yml

Update the authorizer ARN to point to the new one

Update authorizer ARN
